apiVersion: v1
kind: Service
metadata:
  name: {{ include "clamav-openshift.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clamav-openshift.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3310
      protocol: TCP
      name: clamav
  selector:
    {{- include "clamav-openshift.selectorLabels" . | nindent 4 }}
